services:
  fitcontrol:
    image: fitcontrol:latest
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      REDIS_HOST: redis
      FRONTEND_URL: http://localhost:3030
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile-frontend
      args:
        VITE_API_URL: http://localhost:8080
    ports:
      - "3030:80"
    depends_on:
      - fitcontrol

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 5

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH_TOKEN}
    command: http --url=${NGROK_URL} fitcontrol:8080
    stdin_open: true
    tty: true

volumes:
  postgres_data: