spring:
  application:
    name: fitcontrol

  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    locations: classpath:db/migration/public

  mail:
    host: ${SMTP_HOST:?Must set SMTP_HOST env var}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:?Must set SMTP_USERNAME env var}
    password: ${SMTP_PASSWORD:?Must set SMTP_PASSWORD env var}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        from: ${SMTP_FROM:?Must set SMTP_FROM env var}
    default-encoding: utf-8

  messages:
    basename: messages/messages

app:
  jwt:
    secret: ${JWT_SECRET:?Must set JWT_SECRET env var}
    expiration_ms: ${JWT_EXPIRATION_MS:900000}
    issuer: ${JWT_ISSUER:api}

  refresh_token:
    expiration_minutes: ${REFRESH_TOKEN_EXPIRATION_MINUTES:10080}

  migration:
    tenant-location: ${MIGRATION_TENANT_LOCATION:classpath:db/migration/tenant}

  frontend:
    url: ${FRONTEND_URL:?Must set FRONTEND_URL env var}
    set-password-endpoint: ${FRONTEND_PASSWORD_ENDPOINT:set-password}

  gateway:
    secret-key: ${GATEWAY_SECRET_KEY:?Must set GATEWAY_SECRET_KEY env var}
    webhook-key: ${GATEWAY_WEBHOOK_KEY:Must set GATEWAY_WEBHOOK_KEY env var}
    onboarding:
      refresh-url: ${FRONTEND_URL}/stripe/onboarding/refresh
      return-url: ${FRONTEND_URL}/stripe/onboarding/complete