@routineId = 2
@memberId = 1

###
POST {{baseUrl}}/routine
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Push Pull Legs",
  "memberId": 1,
  "days": [
    {
      "exercises": [
        {
          "exerciseId": 1,
          "reps": 12,
          "series": 3
        },
        {
          "exerciseId": 2,
          "reps": 8,
          "series": 4
        }
      ]
    },
    {
      "exercises": [
        {
          "exerciseId": 3,
          "reps": 8,
          "series": 4
        }
      ]
    }
  ]
}

###
GET {{baseUrl}}/routine/{{routineId}}
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/routine/member/{{memberId}}
Authorization: Bearer {{accessToken}}

###
PUT {{baseUrl}}/routine/{{routineId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Updated routine",
  "days": [
    {
      "exercises": [
        {
          "exerciseId": 1,
          "reps": 12,
          "series": 3
        },
        {
          "exerciseId": 2,
          "reps": 8,
          "series": 4
        }
      ]
    },
    {
      "exercises": [
        {
          "exerciseId": 3,
          "reps": 8,
          "series": 4,
          "notes": "Última série até a falha"
        }
      ]
    }
  ]
}

###
DELETE {{baseUrl}}/routine/{{routineId}}
Authorization: Bearer {{accessToken}}